- id: arXiv:2012.10630
  image: https://ojs.aaai.org/public/journals/2/AAAI21Proceedings-Cover-Issue-9.jpg
  repo: decile-team/cords
  date: 2020-12-19
  tags:
    - machine learning
    - efficient machine learning
    - subset selection
    - submodular optimization

- id: http://proceedings.mlr.press/v139/killamsetty21a.html
  image: http://proceedings.mlr.press/v139/assets/images/logo-pmlr.svg
  repo: decile-team/cords
  date: 2020-12-19
  tags:
    - machine learning
    - efficient machine learning
    - subset selection
    - submodular optimization
      